# Generated by Django 3.2.18 on 2024-10-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyData',
        ),
    ]
